include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    close_sinks: ignore
    missing_required_param: error
    missing_return: error

  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/**/l10n/**
    - lib/**/*.g.dart
    - test/**/*.mocks.dart

linter:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: false