name: tvbuddy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  countly_flutter_np: ^23.8.4
  country_codes: ^2.2.0
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  flutter_platform_widgets: ^6.0.2
  flutter_riverpod: ^2.4.5
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  intl: any
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  tmdb_api: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
